### PR TITLE
responsive image size

### PR DESCRIPTION
**Pull request by ssidorenko**
Hello, this is the pull request concerning my quick fix for responsive sizing of a Reel instance.

### CODE REVIEW

**Comment by pisi** [comment]
Thanks for cooperation, Semion! I truly appreciate it.

The code, you've written isn't bad at all, in fact it did help me to realize the merit of this issue. Fixing it this way sure works well for you (and many others, I'm sure), but still there are cases, which need to be covered to roll out the feature. I didn't want to spoil all the fun for you :D, so pieces of code down here are more like hints.

Five points I see right now:
1. `frameChange` may not be the best place. For example if the Reel instance won't be animated, it would not change frame hence no `"frameChange"` event would ever occur, unless user interacts with it (rotates). The `tick.reel` event handler is a place to put this - ticker always ticks regardless the state, so it should give us instant reaction on dimension changes. However the `.css()` call setting new dimensions would surely create additional load, as it there are 36 ticks per second and DOM changes are quite expensive, so we want to limit them just to absolute necessities. However again, simple comparison of dimensions of the image and its container, should perform much better and if dimensions differ, we'd do the `.css()` call just once. In between [lines 1581 and 2](/pisi/Reel/blob/v1.2/jquery.reel.js#L1581) is the place to put such condition.

``` js
if (t.width() != t.parent().width() || t.height() != t.parent().height()){
        // here fix the dimensions
}
```
1. We need to make sure somehow, that `revolution` and `revolution_y` values grows with the dimensions. `revolution`s are used for custom rotational sensitivity. It is a pixel distance needed to be dragged in order to perform one full revolution of the subject. Its size proportions are fixed relative to the stage dimensions (after all, default `revolution` is `2 * width` of stage (or `stitched / 2`)). See [lines 771 and 2](/pisi/Reel/blob/v1.2/jquery.reel.js#L771) what makes up the calculation.

``` js
set(_revolution_, /*new horizontal revolution here*/);
set(_revolution_y_, /*new vertical revolution here*/);
```
1. `dimensions` object data key also needs to reflect the change:

``` js
set(_dimensions_, { x: /* new width here */, y: /* new height here */});
```
1. Sprites. This is where it gets interesting as in this case the sprite is a CSS background image and scaling is not widely supported yet. However, sprites can be scaled by setting `background-size` CSS property and Reel uses it on [line 886](/pisi/Reel/blob/v1.2/jquery.reel.js#L886) already. Note, that I must use vendor specific prefix there to get it working for iphones (it fixes one not completely unrelated issue) and that I use `-webkit-` only. We would probably have to use all vendor prefixes (`-webkit-`, `-moz-`, `-ms-`, `-o-`) to hopefully achieve the scaling effect in all browsers.
2. It needs to have unit tests. This is my part. I will soon push to a new branch tests for some basic aspects of this feature. Hold on. They will guide your coding and ensure everything's where it's supposed to be and nothing got messed up in the process. It will allow both of us to sleep well at night ;)

That should do it I think. Gosh, this is long! I'll let you know when the tests are ready. Please do ask whatever question comes on mind.

**Comment by ssidorenko** [comment]
I've adressed points 1 and 2, tell me what you think !

**Comment by ssidorenko** [comment]
I messed up with this merge, I'll make another pull request later.

**Comment by pisi** [comment]
Oh, sorry to hear. Take any time you want, just please, don't give up! Cheers! :)

**Pull request closed without merging**
